import { ITestParagraph } from '../models/ITestModel.interface';

export const easyParagraph: ITestParagraph = {
  Normal: [
    'In the quiet stillness of a moonlit night,',
    'the world seems to pause and take a',
    'breath. The silver light casts gentle shadows,',
    'transforming familiar landscapes into scenes of serene',
    'beauty. Leaves rustle softly in a gentle',
    'breeze, and the distant hoot of an',
    'owl adds a touch of mystery to',
    'the tranquil atmosphere. This is a time',
    'when thoughts drift effortlessly, and the worries',
    'of the day fade into the background.',
    'The night, with its calming presence, offers',
    'a moment of reflection and peace, inviting',
    'all who are awake to bask in',
    'its quiet splendor.',
    'The gentle hum of the city awakened me early',
    'this morning, a soundscape composed of distant car horns,',
    'the occasional chirp of birds, and the ever-present murmur',
    'of human activity. As I stepped outside, the air',
    "was cool and refreshing, a reminder that summer's",
    'heat had not yet fully claimed the days.',
    'The sky, painted in shades of soft pastels,',
    'hinted at the promise of a beautiful sunrise.',
    'I took a deep breath, savoring the moment',
    'of quiet before the day’s hustle began.',
    'Walking down the familiar streets, I marveled at',
    'the blend of nature and urban life, where',
    'trees lined the sidewalks and flowers peeked out',
    'from tiny patches of green amidst the concrete.',
    'It struck me how life, in its myriad forms,',
    'thrived even in the most unexpected places. This brief',
    'morning reverie filled me with a sense of calm',
    'and readiness to face whatever challenges lay ahead.',
  ],
  Pro: "In the quiet stillness of a moonlit night, the world seems to pause and take a breath. The silver light casts gentle shadows, transforming familiar landscapes into scenes of serene beauty. Leaves rustle softly in a gentle breeze, and the distant hoot of an owl adds a touch of mystery to the tranquil atmosphere. This is a time when thoughts drift effortlessly, and the worries of the day fade into the background. The night, with its calming presence, offers a moment of reflection and peace, inviting all who are awake to bask in its quiet splendor.The gentle hum of the city awakened me early this morning, a soundscape composed of distant car horns, the occasional chirp of birds, and the ever-present murmur of human activity. As I stepped outside, the air was cool and refreshing, a reminder that summer's heat had not yet fully claimed the days. The sky, painted in shades of soft pastels, hinted at the promise of a beautiful sunrise. I took a deep breath, savoring the moment of quiet before the day’s hustle began. Walking down the familiar streets, I marveled at the blend of nature and urban life, where trees lined the sidewalks and flowers peeked out from tiny patches of green amidst the concrete. It struck me how life, in its myriad forms, thrived even in the most unexpected places. This brief morning reverie filled me with a sense of calm and readiness to face whatever challenges lay ahead.",
};

export const mediumParagraph: ITestParagraph = {
  Normal: [
    'In the quiet stillness of a moonlit night,',
    'the world seems to pause and take a',
    'breath. The silver light casts gentle shadows,',
    'transforming familiar landscapes into scenes of serene',
    'beauty. Leaves rustle softly in a gentle',
    'breeze, and the distant hoot of an',
    'owl adds a touch of mystery to',
    'the tranquil atmosphere. This is a time',
    'when thoughts drift effortlessly, and the worries',
    'of the day fade into the background.',
    'The night, with its calming presence, offers',
    'a moment of reflection and peace, inviting',
    'all who are awake to bask in',
    'its quiet splendor.',
    'The gentle hum of the city awakened me early',
    'this morning, a soundscape composed of distant car horns,',
    'the occasional chirp of birds, and the ever-present murmur',
    'of human activity. As I stepped outside, the air',
    "was cool and refreshing, a reminder that summer's",
    'heat had not yet fully claimed the days.',
    'The sky, painted in shades of soft pastels,',
    'hinted at the promise of a beautiful sunrise.',
    'I took a deep breath, savoring the moment',
    'of quiet before the day’s hustle began.',
    'Walking down the familiar streets, I marveled at',
    'the blend of nature and urban life, where',
    'trees lined the sidewalks and flowers peeked out',
    'from tiny patches of green amidst the concrete.',
    'It struck me how life, in its myriad forms,',
    'thrived even in the most unexpected places. This brief',
    'morning reverie filled me with a sense of calm',
    'and readiness to face whatever challenges lay ahead.',
  ],
  Pro: "In the quiet stillness of a moonlit night, the world seems to pause and take a breath. The silver light casts gentle shadows, transforming familiar landscapes into scenes of serene beauty. Leaves rustle softly in a gentle breeze, and the distant hoot of an owl adds a touch of mystery to the tranquil atmosphere. This is a time when thoughts drift effortlessly, and the worries of the day fade into the background. The night, with its calming presence, offers a moment of reflection and peace, inviting all who are awake to bask in its quiet splendor.The gentle hum of the city awakened me early this morning, a soundscape composed of distant car horns, the occasional chirp of birds, and the ever-present murmur of human activity. As I stepped outside, the air was cool and refreshing, a reminder that summer's heat had not yet fully claimed the days. The sky, painted in shades of soft pastels, hinted at the promise of a beautiful sunrise. I took a deep breath, savoring the moment of quiet before the day’s hustle began. Walking down the familiar streets, I marveled at the blend of nature and urban life, where trees lined the sidewalks and flowers peeked out from tiny patches of green amidst the concrete. It struck me how life, in its myriad forms, thrived even in the most unexpected places. This brief morning reverie filled me with a sense of calm and readiness to face whatever challenges lay ahead.",
};

export const hardParagraph: ITestParagraph = {
  Normal: [
    'In the quiet stillness of a moonlit night,',
    'the world seems to pause and take a',
    'breath. The silver light casts gentle shadows,',
    'transforming familiar landscapes into scenes of serene',
    'beauty. Leaves rustle softly in a gentle',
    'breeze, and the distant hoot of an',
    'owl adds a touch of mystery to',
    'the tranquil atmosphere. This is a time',
    'when thoughts drift effortlessly, and the worries',
    'of the day fade into the background.',
    'The night, with its calming presence, offers',
    'a moment of reflection and peace, inviting',
    'all who are awake to bask in',
    'its quiet splendor.',
    'The gentle hum of the city awakened me early',
    'this morning, a soundscape composed of distant car horns,',
    'the occasional chirp of birds, and the ever-present murmur',
    'of human activity. As I stepped outside, the air',
    "was cool and refreshing, a reminder that summer's",
    'heat had not yet fully claimed the days.',
    'The sky, painted in shades of soft pastels,',
    'hinted at the promise of a beautiful sunrise.',
    'I took a deep breath, savoring the moment',
    'of quiet before the day’s hustle began.',
    'Walking down the familiar streets, I marveled at',
    'the blend of nature and urban life, where',
    'trees lined the sidewalks and flowers peeked out',
    'from tiny patches of green amidst the concrete.',
    'It struck me how life, in its myriad forms,',
    'thrived even in the most unexpected places. This brief',
    'morning reverie filled me with a sense of calm',
    'and readiness to face whatever challenges lay ahead.',
  ],
  Pro: "In the quiet stillness of a moonlit night, the world seems to pause and take a breath. The silver light casts gentle shadows, transforming familiar landscapes into scenes of serene beauty. Leaves rustle softly in a gentle breeze, and the distant hoot of an owl adds a touch of mystery to the tranquil atmosphere. This is a time when thoughts drift effortlessly, and the worries of the day fade into the background. The night, with its calming presence, offers a moment of reflection and peace, inviting all who are awake to bask in its quiet splendor.The gentle hum of the city awakened me early this morning, a soundscape composed of distant car horns, the occasional chirp of birds, and the ever-present murmur of human activity. As I stepped outside, the air was cool and refreshing, a reminder that summer's heat had not yet fully claimed the days. The sky, painted in shades of soft pastels, hinted at the promise of a beautiful sunrise. I took a deep breath, savoring the moment of quiet before the day’s hustle began. Walking down the familiar streets, I marveled at the blend of nature and urban life, where trees lined the sidewalks and flowers peeked out from tiny patches of green amidst the concrete. It struck me how life, in its myriad forms, thrived even in the most unexpected places. This brief morning reverie filled me with a sense of calm and readiness to face whatever challenges lay ahead.",
};
